run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - revive
    - gocyclo
    - ineffassign
    - misspell
    - gocritic
    - gosec
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - gosimple
    - staticcheck
    - stylecheck
    - shadow

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    min-confidence: 0.8
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gosec:
    excludes:
      - G404  # Use of weak random number generator

issues:
  exclude-dirs:
    - prisma/db
    - tmp
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    - path: mock_.*\.go
      linters:
        - revive
        - errcheck
        - dupl

  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 3

output:
  formats:
    - colored-line-number
  print-issued-lines: true
  print-linter-name: true