coverage:
  status:
    project:
      default:
        # basic
        target: 100%
        threshold: 0%
        base: auto
        # advanced
        branches:
          - main
        if_ci_failed: error
        only_pulls: false
        flags:
          - unittests
        paths:
          - internal
    patch:
      default:
        target: 100%
  
  parsers:
    go:
      partials_as_hits: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

ignore:
  - docs/*
  - scripts/*
  - prisma/*
  - "*.md"